### ISSUE TITLE
[FEAT] 메인 화면 UI 구현

### ISSUE THREAD

**Issue by Taehyeon-Kim** [RxSwift-Study-with-Potatoes/RxSwift-Basic-Exercise#2]
## 📌  Feature Issue

메인 화면의 UI를 구성합니다.  
각 뷰로 이동 시 사용할 버튼을 배치합니다.
(저 세상 디자인이기는 하지만 나중에 시간되면 수정하는걸로 하겠습니다.)

<img src = "https://user-images.githubusercontent.com/61109660/131488927-651c5409-fec6-48a8-b04c-8d3314606603.png" width = "300" />

## 📝  To-do

- [x] 필요 이미지 에셋 추가
- [x] Shadow, Corner Radius 익스텐션 추가
- [x] UI 구현
- [x] 화면 연결 (지원이가 만들어놓은 뷰 컨까지)
